name: sma_energy_app
description: SMA Energy App - Flutter port of the React sitemap mockup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.4.10
  go_router: 12.0.3
  fl_chart: 0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
